#+HUGO_BASE_DIR: ../
#+author: Gautam Manohar

* Home
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_FILE_NAME: _index
:END:
** Voraciously curious. Ceaselessly skeptical. Unabashedly nerdy.
If any of these terms describe you, then great!
You're in the right place.
I'm Gautam.
Welcome to my personal website.
You can find my many curious, skeptical, and nerdy thoughts on my [[/blog/][blog]].

I love mathematics, and I learn computer science and chemistry on the side.
I firmly believe in the power of ideas.
Interesting ideas come from all walks of life: academic subjects, learning a new language, meeting new people, or idle musings over a good cup of tea.
Such ideas give my life colour and promise to occupy me for a lifetime.

** A good problem is never solved.
The most fulfilling problems lead not just to answers that satisfy inquiry but to questions that further it.
After all, what is an interesting idea without a question to inspire it?
Questions are the ultimate companion to a lifelong learner (non-human, of course).
They motivate me to rejoice in spite of failure and work hard in spite of success.
The path paved by interesting questions never ends---and that's what's so exciting about it!

** Here's some more about me.
I'm a Grade 11 student at the [[https://utschools.ca][University of Toronto Schools (UTS)]].
My favourite number is 7, but perhaps it should be $n$: why consider one when you can consider them all?
My favourite anime series in Steins;Gate, and my favourite infinite series is Fourier; it seems I like time.
Speaking of time, when I have some lying around, I like to practice my handwriting and calligraphy, play table tennis, and watch basketball.

* Blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:EXPORT_FILE_NAME: _index
:END:

** Math                                                               :@math:
:PROPERTIES:
:EXPORT_HUGO_SECTION: math
:EXPORT_FILE_NAME: _index
:END:

*** Comparing $e^\pi$ and $\pi^e$                            :calculus:proof:
:PROPERTIES:
:EXPORT_FILE_NAME: e-pi
:EXPORT_DATE: 2018-02-01
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :shorttitle "Comparing Powers of e and pi"
:EXPORT_DESCRIPTION: "Which is greater: e^pi or pi^e? I solve this puzzle with differentiation, Taylor series, concavity, and the arithmetic-geometric mean inequality."
:END:
Test.

* Footnotes
* COMMENT Local Variables                                                   :ARCHIVE:
# Local Variables:
# eval: (add-hook 'after-save-hook #'org-hugo-export-wim-to-md-after-save :append :local)
# End:
